BITWISE_BUILTIN_BIT = { type = "u256", value = "4", comment = "4" }
BITWISE__RATIO = { type = "u256", value = "8", comment = "8" }
BITWISE__ROW_RATIO = { type = "u256", value = "128", comment = "128" }
COMMITMENT_MASK = { type = "u256", value = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000000", comment = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000000" }
COMMITMENT_SIZE_IN_BYTES = { type = "u64", value = "0x20", comment = "0x20" }
CONSTRAINTS_DEGREE_BOUND = { type = "u64", value = "2", comment = "2" }
CONTINUOUS_PAGE = { type = "u256", value = "1", comment = "1" }
DILUTED_N_BITS = { type = "u256", value = "16", comment = "16" }
DILUTED_SPACING = { type = "u8", value = "4", comment = "4" }
ECDSA_BUILTIN_BIT = { type = "u256", value = "3", comment = "3" }
EC_OP_BUILTIN_BIT = { type = "u256", value = "5", comment = "5" }
FINAL_PC = { type = "u64", value = "INITIAL_PC + 4", comment = "INITIAL_PC + 4" }
FRI_CTX_SIZE = { type = "u256", value = "FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET + (FRI_GROUP_SIZE / 2)", comment = "FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET + (FRI_GROUP_SIZE / 2)" }
FRI_CTX_TO_COSET_EVALUATIONS_OFFSET = { type = "u256", value = "0", comment = "0" }
FRI_CTX_TO_FRI_GROUP_OFFSET = { type = "u256", value = "FRI_GROUP_SIZE", comment = "FRI_GROUP_SIZE" }
FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET = { type = "u256", value = "FRI_CTX_TO_FRI_GROUP_OFFSET + FRI_GROUP_SIZE", comment = "FRI_CTX_TO_FRI_GROUP_OFFSET + FRI_GROUP_SIZE" }
FRI_GROUP_GEN = { type = "u256", value = "0x5ec467b88826aba4537602d514425f3b0bdf467bbf302458337c45f6021e539", comment = "0x5ec467b88826aba4537602d514425f3b0bdf467bbf302458337c45f6021e539" }
FRI_GROUP_SIZE = { type = "u256", value = "0x20 * MAX_COSET_SIZE", comment = "0x20 * MAX_COSET_SIZE" }
FRI_MAX_STEP_SIZE = { type = "u256", value = "4", comment = "4" }
FRI_MIN_STEP_SIZE = { type = "u256", value = "2", comment = "2" }
FRI_QUEUE_SIZE = { type = "u64", value = "MAX_N_QUERIES", comment = "MAX_N_QUERIES" }
FRI_QUEUE_SLOT_SIZE = { type = "u64", value = "3", comment = "3" }
FRI_QUEUE_SLOT_SIZE_IN_BYTES = { type = "u256", value = "3 * 0x20", comment = "3 * 0x20" }
GENERATOR_VAL = { type = "u256", value = "3", comment = "3" }
INDEX_SIZE_IN_BYTES = { type = "u64", value = "0x20", comment = "0x20" }
INITIAL_PC = { type = "u64", value = "1", comment = "1" }
KECCAK_BUILTIN_BIT = { type = "u256", value = "6", comment = "6" }
K_MODULUS = { type = "u256", value = "0x800000000000011000000000000000000000000000000000000000000000001", comment = "0x800000000000011000000000000000000000000000000000000000000000001" }
K_MODULUS_TIMES_16 = { type = "u256", value = "0x8000000000000110000000000000000000000000000000000000000000000010", comment = "0x8000000000000110000000000000000000000000000000000000000000000010" }
K_MONTGOMERY_R = { type = "u256", value = "0x7fffffffffffdf0ffffffffffffffffffffffffffffffffffffffffffffffe1", comment = "0x7fffffffffffdf0ffffffffffffffffffffffffffffffffffffffffffffffe1" }
K_MONTGOMERY_R_INV = { type = "u256", value = "0x40000000000001100000000000012100000000000000000000000000000000", comment = "0x40000000000001100000000000012100000000000000000000000000000000" }
LAYOUT_CODE = { type = "u256", value = "42800643258479064999893963318903811951182475189843316", comment = "42800643258479064999893963318903811951182475189843316" }
LOG_CPU_COMPONENT_HEIGHT = { type = "u256", value = "4", comment = "4" }
MASK_SIZE = { type = "u64", value = "192", comment = "192" }
MAX_COSET_SIZE = { type = "u256", value = "1 << FRI_MAX_STEP_SIZE", comment = "2^FRI_MAX_STEP_SIZE" }
MAX_FRI_STEPS = { type = "u64", value = "10", comment = "10" }
MAX_N_MERKLE_VERIFIER_QUERIES = { type = "u64", value = "128", comment = "128" }
MAX_N_QUERIES = { type = "u64", value = "48", comment = "48" }
MAX_SUPPORTED_FRI_STEP_SIZE = { type = "u64", value = "4", comment = "4" }
MEMORY_PAIR_SIZE = { type = "u256", value = "2", comment = "2" }
MERKLE_SLOT_SIZE_IN_BYTES = { type = "u64", value = "0x40", comment = "0x40" }
METADATA_OFFSET_TASK_N_TREE_PAIRS = { type = "u64", value = "2", comment = "2" }
METADATA_OFFSET_TASK_OUTPUT_SIZE = { type = "u64", value = "0", comment = "0" }
METADATA_OFFSET_TASK_PROGRAM_HASH = { type = "u64", value = "1", comment = "1" }
METADATA_TASKS_OFFSET = { type = "u64", value = "1", comment = "1" }
METADATA_TASK_HEADER_SIZE = { type = "u64", value = "3", comment = "3" }
MM_BLOW_UP_FACTOR = { type = "u64", value = "0x1", comment = "0x1" }
MM_CHANNEL = { type = "u64", value = "0xa", comment = "0xa" }
MM_COMPOSITION_ALPHA = { type = "u64", value = "0x166", comment = "0x166" }
MM_COMPOSITION_OODS_VALUES = { type = "u64", value = "0x227", comment = "0x227" }
MM_COMPOSITION_QUERY_RESPONSES = { type = "u64", value = "0x49a", comment = "0x49a" }
MM_CONSTRAINT_POLY_ARGS_END = { type = "u64", value = "0x227", comment = "0x227" }
MM_CONSTRAINT_POLY_ARGS_START = { type = "u64", value = "0x13d", comment = "0x13d" }
MM_CONTEXT_SIZE = { type = "u64", value = "0x4fd", comment = "0x4fd" }
MM_DILUTED_CHECK__FINAL_CUM_VAL = { type = "u64", value = "0x157", comment = "0x157" }
MM_DILUTED_CHECK__FIRST_ELM = { type = "u64", value = "0x154", comment = "0x154" }
MM_DILUTED_CHECK__INTERACTION_ALPHA = { type = "u64", value = "0x156", comment = "0x156" }
MM_DILUTED_CHECK__INTERACTION_Z = { type = "u64", value = "0x155", comment = "0x155" }
MM_DILUTED_CHECK__PERMUTATION__INTERACTION_ELM = { type = "u64", value = "0x152", comment = "0x152" }
MM_DILUTED_CHECK__PERMUTATION__PUBLIC_MEMORY_PROD = { type = "u64", value = "0x153", comment = "0x153" }
MM_EVAL_DOMAIN_GENERATOR = { type = "u64", value = "0x4", comment = "0x4" }
MM_EVAL_DOMAIN_SIZE = { type = "u64", value = "0x0", comment = "0x0" }
MM_FINAL_AP = { type = "u64", value = "0x149", comment = "0x149" }
MM_FINAL_PC = { type = "u64", value = "0x14a", comment = "0x14a" }
MM_FRI_COMMITMENTS = { type = "u64", value = "0x131", comment = "0x131" }
MM_FRI_CTX = { type = "u64", value = "0xfe", comment = "0xfe" }
MM_FRI_EVAL_POINTS = { type = "u64", value = "0x127", comment = "0x127" }
MM_FRI_LAST_LAYER_DEG_BOUND = { type = "u64", value = "0x13b", comment = "0x13b" }
MM_FRI_LAST_LAYER_PTR = { type = "u64", value = "0x13c", comment = "0x13c" }
MM_FRI_QUERIES_DELIMITER = { type = "u64", value = "0xfd", comment = "0xfd" }
MM_FRI_QUEUE = { type = "u64", value = "0x6d", comment = "0x6d" }
MM_FRI_STEP_SIZES_PTR = { type = "u64", value = "0x126", comment = "0x126" }
MM_HALF_OFFSET_SIZE = { type = "u64", value = "0x146", comment = "0x146" }
MM_INITIAL_AP = { type = "u64", value = "0x147", comment = "0x147" }
MM_INITIAL_BITWISE_ADDR = { type = "u64", value = "0x15c", comment = "0x15c" }
MM_INITIAL_PC = { type = "u64", value = "0x148", comment = "0x148" }
MM_INITIAL_PEDERSEN_ADDR = { type = "u64", value = "0x15a", comment = "0x15a" }
MM_INITIAL_POSEIDON_ADDR = { type = "u64", value = "0x15d", comment = "0x15d" }
MM_INITIAL_RANGE_CHECK_ADDR = { type = "u64", value = "0x15b", comment = "0x15b" }
MM_INTERACTION_ELEMENTS = { type = "u64", value = "0x160", comment = "0x160" }
MM_LOG_EVAL_DOMAIN_SIZE = { type = "u64", value = "0x2", comment = "0x2" }
MM_LOG_N_STEPS = { type = "u64", value = "0x4fa", comment = "0x4fa" }
MM_MEMORY__MULTI_COLUMN_PERM__HASH_INTERACTION_ELM0 = { type = "u64", value = "0x14c", comment = "0x14c" }
MM_MEMORY__MULTI_COLUMN_PERM__PERM__INTERACTION_ELM = { type = "u64", value = "0x14b", comment = "0x14b" }
MM_MEMORY__MULTI_COLUMN_PERM__PERM__PUBLIC_MEMORY_PROD = { type = "u64", value = "0x14d", comment = "0x14d" }
MM_MERKLE_QUEUE = { type = "u64", value = "0xd", comment = "0xd" }
MM_N_PUBLIC_MEM_ENTRIES = { type = "u64", value = "0x4fb", comment = "0x4fb" }
MM_N_PUBLIC_MEM_PAGES = { type = "u64", value = "0x4fc", comment = "0x4fc" }
MM_N_UNIQUE_QUERIES = { type = "u64", value = "0x9", comment = "0x9" }
MM_OFFSET_SIZE = { type = "u64", value = "0x145", comment = "0x145" }
MM_OODS_ALPHA = { type = "u64", value = "0x259", comment = "0x259" }
MM_OODS_COMMITMENT = { type = "u64", value = "0x8", comment = "0x8" }
MM_OODS_EVAL_POINTS = { type = "u64", value = "0x229", comment = "0x229" }
MM_OODS_POINT = { type = "u64", value = "0x15f", comment = "0x15f" }
MM_OODS_VALUES = { type = "u64", value = "0x167", comment = "0x167" }
MM_PEDERSEN__SHIFT_POINT_X = { type = "u64", value = "0x158", comment = "0x158" }
MM_PEDERSEN__SHIFT_POINT_Y = { type = "u64", value = "0x159", comment = "0x159" }
MM_PERIODIC_COLUMN__PEDERSEN__POINTS__X = { type = "u64", value = "0x13d", comment = "0x13d" }
MM_PERIODIC_COLUMN__PEDERSEN__POINTS__Y = { type = "u64", value = "0x13e", comment = "0x13e" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY0 = { type = "u64", value = "0x13f", comment = "0x13f" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY1 = { type = "u64", value = "0x140", comment = "0x140" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY2 = { type = "u64", value = "0x141", comment = "0x141" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__PARTIAL_ROUND_KEY0 = { type = "u64", value = "0x142", comment = "0x142" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__PARTIAL_ROUND_KEY1 = { type = "u64", value = "0x143", comment = "0x143" }
MM_PROOF_OF_WORK_BITS = { type = "u64", value = "0x3", comment = "0x3" }
MM_PUBLIC_INPUT_PTR = { type = "u64", value = "0x5", comment = "0x5" }
MM_RANGE_CHECK16__PERM__INTERACTION_ELM = { type = "u64", value = "0x14e", comment = "0x14e" }
MM_RANGE_CHECK16__PERM__PUBLIC_MEMORY_PROD = { type = "u64", value = "0x14f", comment = "0x14f" }
MM_RANGE_CHECK_MAX = { type = "u64", value = "0x151", comment = "0x151" }
MM_RANGE_CHECK_MIN = { type = "u64", value = "0x150", comment = "0x150" }
MM_TRACE_COMMITMENT = { type = "u64", value = "0x6", comment = "0x6" }
MM_TRACE_GENERATOR = { type = "u64", value = "0x15e", comment = "0x15e" }
MM_TRACE_LENGTH = { type = "u64", value = "0x144", comment = "0x144" }
MM_TRACE_QUERY_RESPONSES = { type = "u64", value = "0x25a", comment = "0x25a" }
N_COEFFICIENTS = { type = "u256", value = "124", comment = "124" }
N_COLUMNS_IN_MASK = { type = "u64", value = "12", comment = "12" }
N_COLUMNS_IN_TRACE0 = { type = "u64", value = "9", comment = "9" }
N_COLUMNS_IN_TRACE1 = { type = "u64", value = "3", comment = "3" }
N_INTERACTION_ELEMENTS = { type = "u64", value = "6", comment = "6" }
N_OODS_COEFFICIENTS = { type = "u64", value = "N_OODS_VALUES", comment = "N_OODS_VALUES" }
N_OODS_VALUES = { type = "u64", value = "MASK_SIZE + CONSTRAINTS_DEGREE_BOUND", comment = "MASK_SIZE + CONSTRAINTS_DEGREE_BOUND" }
N_ROWS_IN_MASK = { type = "u256", value = "98", comment = "98" }
OFFSET_BITWISE_BEGIN_ADDR = { type = "u64", value = "14", comment = "14" }
OFFSET_BITWISE_STOP_ADDR = { type = "u64", value = "15", comment = "15" }
OFFSET_EXECUTION_BEGIN_ADDR = { type = "u64", value = "6", comment = "6" }
OFFSET_EXECUTION_STOP_PTR = { type = "u64", value = "7", comment = "7" }
OFFSET_LAYOUT_CODE = { type = "u64", value = "3", comment = "3" }
OFFSET_LOG_N_STEPS = { type = "u64", value = "0", comment = "0" }
OFFSET_N_PUBLIC_MEMORY_PAGES = { type = "u64", value = "20", comment = "20" }
OFFSET_OUTPUT_BEGIN_ADDR = { type = "u64", value = "8", comment = "8" }
OFFSET_OUTPUT_STOP_PTR = { type = "u64", value = "9", comment = "9" }
OFFSET_PEDERSEN_BEGIN_ADDR = { type = "u64", value = "10", comment = "10" }
OFFSET_PEDERSEN_STOP_PTR = { type = "u64", value = "11", comment = "11" }
OFFSET_POSEIDON_BEGIN_ADDR = { type = "u64", value = "16", comment = "16" }
OFFSET_POSEIDON_STOP_PTR = { type = "u64", value = "17", comment = "17" }
OFFSET_PROGRAM_BEGIN_ADDR = { type = "u64", value = "4", comment = "4" }
OFFSET_PROGRAM_STOP_PTR = { type = "u64", value = "5", comment = "5" }
OFFSET_PUBLIC_MEMORY = { type = "u64", value = "21", comment = "21" }
OFFSET_PUBLIC_MEMORY_PADDING_ADDR = { type = "u64", value = "18", comment = "18" }
OFFSET_PUBLIC_MEMORY_PADDING_VALUE = { type = "u64", value = "19", comment = "19" }
OFFSET_RANGE_CHECK_BEGIN_ADDR = { type = "u64", value = "12", comment = "12" }
OFFSET_RANGE_CHECK_STOP_PTR = { type = "u64", value = "13", comment = "13" }
OFFSET_RC_MAX = { type = "u64", value = "2", comment = "2" }
OFFSET_RC_MIN = { type = "u64", value = "1", comment = "1" }
ONE_VAL = { type = "u256", value = "1", comment = "1" }
OUTPUT_BUILTIN_BIT = { type = "u256", value = "0", comment = "0" }
PAGE_INFO_ADDRESS_OFFSET = { type = "u256", value = "0", comment = "0" }
PAGE_INFO_HASH_OFFSET = { type = "u256", value = "2", comment = "2" }
PAGE_INFO_SIZE = { type = "u256", value = "3", comment = "3" }
PAGE_INFO_SIZE_IN_BYTES = { type = "u256", value = "3 * 32", comment = "3 * 32" }
PAGE_INFO_SIZE_OFFSET = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_BIT = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_RATIO = { type = "u256", value = "128", comment = "128" }
PEDERSEN_BUILTIN_REPETITIONS = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_ROW_RATIO = { type = "u256", value = "2048", comment = "2048" }
POSEIDON_BUILTIN_BIT = { type = "u256", value = "7", comment = "7" }
POSEIDON__M = { type = "u256", value = "3", comment = "3" }
POSEIDON__RATIO = { type = "u256", value = "8", comment = "8" }
POSEIDON__ROUNDS_FULL = { type = "u256", value = "8", comment = "8" }
POSEIDON__ROUNDS_PARTIAL = { type = "u256", value = "83", comment = "83" }
POSEIDON__ROW_RATIO = { type = "u256", value = "128", comment = "128" }
PROGRAM_SIZE = { type = "u256", value = "728", comment = "728" }
PROOF_PARAMS_FRI_STEPS_OFFSET = { type = "u64", value = "5", comment = "5" }
PROOF_PARAMS_N_FRI_STEPS_OFFSET = { type = "u64", value = "4", comment = "4" }
PUBLIC_MEMORY_STEP = { type = "u256", value = "16", comment = "16" }
RANGE_CHECK_BUILTIN_BIT = { type = "u256", value = "2", comment = "2" }
RANGE_CHECK_BUILTIN_RATIO = { type = "u256", value = "8", comment = "8" }
RANGE_CHECK_BUILTIN_ROW_RATIO = { type = "u256", value = "128", comment = "128" }
RANGE_CHECK_N_PARTS = { type = "u256", value = "8", comment = "8" }
REGULAR_PAGE = { type = "u256", value = "0", comment = "0" }
TWO_COMMITMENTS_SIZE_IN_BYTES = { type = "u64", value = "0x40", comment = "0x40" }
