BITWISE_BUILTIN_BIT = { type = "u256", value = "4", comment = "4" }
BITWISE__RATIO = { type = "u256", value = "8", comment = "8" }
BITWISE__ROW_RATIO = { type = "u256", value = "128", comment = "128" }
BLOCK_HASH_OFFSET = { type = "u64", value = "3", comment = "3" }
BLOCK_NUMBER_OFFSET = { type = "u64", value = "2", comment = "2" }
BLS_MODULUS = { type = "u256", value = "52435875175126190479447740508185965837690552500527637822603658699938581184513", comment = "52435875175126190479447740508185965837690552500527637822603658699938581184513" }
BYTES_PER_COMMITMENT = { type = "u64", value = "48", comment = "48" }
BYTES_PER_FIELD_ELEMENT = { type = "u64", value = "32", comment = "32" }
BYTES_PER_PROOF = { type = "u64", value = "48", comment = "48" }
COMMITMENT_MASK = { type = "u256", value = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000000", comment = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000000" }
COMMITMENT_SIZE_IN_BYTES = { type = "u64", value = "0x20", comment = "32" }
CONFIG_HASH_OFFSET = { type = "u64", value = "4", comment = "4" }
CONFIG_HASH_TAG = { type = "vector<u8>", value = 'b"STARKNET_1.0_STARKNET_CONFIG_HASH"', comment = "The hash of the StarkNet config" }
CONSTRAINTS_DEGREE_BOUND = { type = "u64", value = "2", comment = "2" }
CONTINUOUS_PAGE = { type = "u256", value = "1", comment = "1" }
DILUTED_N_BITS = { type = "u256", value = "16", comment = "16" }
DILUTED_SPACING = { type = "u8", value = "4", comment = "4" }
ECDSA_BUILTIN_BIT = { type = "u256", value = "3", comment = "3" }
EC_OP_BUILTIN_BIT = { type = "u256", value = "5", comment = "5" }
EINVALID_BLOCK_NUMBER = { type = "u64", value = "131073", comment = "131073" }
EINVALID_CONFIG_HASH = { type = "u64", value = "131075", comment = "131075" }
EINVALID_FINAL_BLOCK_NUMBER = { type = "u64", value = "262151", comment = "262151" }
EINVALID_KZG_COMMITMENT = { type = "u64", value = "327685", comment = "327685" }
EINVALID_KZG_COMMITMENT_SIZE = { type = "u64", value = "327687", comment = "327687" }
EINVALID_KZG_PROOF_SIZE = { type = "u64", value = "327683", comment = "327683" }
EINVALID_KZG_SEGMENT_SIZE = { type = "u64", value = "327682", comment = "327682" }
EINVALID_MESSAGE_SEGMENT_SIZE = { type = "u64", value = "262145", comment = "262145" }
EINVALID_MESSAGE_TO_CONSUME = { type = "u64", value = "262149", comment = "262149" }
EINVALID_PAYLOAD_LENGTH = { type = "u64", value = "262147", comment = "262147" }
EINVALID_PREVIOUS_ROOT = { type = "u64", value = "131074", comment = "131074" }
EINVALID_PRE_COMPILE_INPUT_SIZE = { type = "u64", value = "327684", comment = "327684" }
EINVALID_Y_VALUE = { type = "u64", value = "327686", comment = "327686" }
EINVALID_Z_VALUE = { type = "u64", value = "327688", comment = "327688" }
EMESSAGE_TOO_SHORT = { type = "u64", value = "262146", comment = "262146" }
ENAMED_STORAGE_ALREADY_SET = { type = "u64", value = "196609", comment = "196609" }
ENO_STATE_TRANSITION_PROOF = { type = "u64", value = "393217", comment = "393217" }
EPOINT_EVALUATION_PRECOMPILE_CALL_FAILED = { type = "u64", value = "32769", comment = "32769" }
ESTARKNET_OUTPUT_TOO_LONG = { type = "u64", value = "262150", comment = "262150" }
ESTARKNET_OUTPUT_TOO_SHORT = { type = "u64", value = "262152", comment = "262152" }
ETRUNCATED_MESSAGE_PAYLOAD = { type = "u64", value = "262148", comment = "262148" }
EUNEXPECTED_BLOB_HASH_VERSION = { type = "u64", value = "458753", comment = "458753" }
EUNEXPECTED_KZG_DA_FLAG = { type = "u64", value = "327681", comment = "327681" }
EUNEXPECTED_POINT_EVALUATION_PRECOMPILE_OUTPUT = { type = "u64", value = "524290", comment = "524290" }
EUNEXPECTED_VERSION_HASH = { type = "u64", value = "458754", comment = "458754" }
FIELD_ELEMENTS_PER_BLOB = { type = "u256", value = "4096", comment = "4096" }
FINAL_PC = { type = "u64", value = "INITIAL_PC + 4", comment = "INITIAL_PC + 4" }
FRI_CTX_SIZE = { type = "u256", value = "FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET + (FRI_GROUP_SIZE / 2)", comment = "FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET + (FRI_GROUP_SIZE / 2)" }
FRI_CTX_TO_COSET_EVALUATIONS_OFFSET = { type = "u256", value = "0", comment = "0" }
FRI_CTX_TO_FRI_GROUP_OFFSET = { type = "u256", value = "FRI_GROUP_SIZE", comment = "FRI_GROUP_SIZE" }
FRI_CTX_TO_FRI_HALF_INV_GROUP_OFFSET = { type = "u256", value = "FRI_CTX_TO_FRI_GROUP_OFFSET + FRI_GROUP_SIZE", comment = "FRI_CTX_TO_FRI_GROUP_OFFSET + FRI_GROUP_SIZE" }
FRI_GROUP_GEN = { type = "u256", value = "0x5ec467b88826aba4537602d514425f3b0bdf467bbf302458337c45f6021e539", comment = "2679026602897868112349604024891625875968950767352485125058791696935099163961" }
FRI_GROUP_SIZE = { type = "u256", value = "32 * MAX_COSET_SIZE", comment = "32 * MAX_COSET_SIZE" }
FRI_MAX_STEP_SIZE = { type = "u256", value = "4", comment = "4" }
FRI_MIN_STEP_SIZE = { type = "u256", value = "2", comment = "2" }
FRI_QUEUE_SIZE = { type = "u64", value = "MAX_N_QUERIES", comment = "MAX_N_QUERIES" }
FRI_QUEUE_SLOT_SIZE = { type = "u64", value = "3", comment = "3" }
FRI_QUEUE_SLOT_SIZE_IN_BYTES = { type = "u256", value = "3 * 32", comment = "3 * 32" }
G1_GENERATOR = { type = "vector<u8>", value = 'x"97f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb"', comment = "G1 Generator" }
G2S_SETUP = { type = "vector<u8>", value = 'x"b5bfd7dd8cdeb128843bc287230af38926187075cbfbefa81009a2ce615ac53d2914e5870cb452d2afaaab24f3499f72185cbfee53492714734429b7b38608e23926c911cceceac9a36851477ba4c60b087041de621000edc98edada20c1def2"', comment = "G2 secret" }
G2_GENERATOR = { type = "vector<u8>", value = 'x"93e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8"', comment = "G2 generator" }
GENERATOR_VAL = { type = "u256", value = "3", comment = "3" }
HEADER_SIZE = { type = "u64", value = "6", comment = "6" }
INDEX_SIZE_IN_BYTES = { type = "u64", value = "32", comment = "32" }
INITIAL_PC = { type = "u64", value = "1", comment = "1" }
KECCAK_BUILTIN_BIT = { type = "u256", value = "6", comment = "6" }
KZG_SEGMENT_SIZE = { type = "u64", value = "5", comment = "5" }
K_MODULUS = { type = "u256", value = "0x800000000000011000000000000000000000000000000000000000000000001", comment = "3618502788666131213697322783095070105623107215331596699973092056135872020481" }
K_MODULUS_TIMES_16 = { type = "u256", value = "0x8000000000000110000000000000000000000000000000000000000000000010", comment = "57896044618658099419157164529521121689969715445305547199569472898173952327696" }
K_MONTGOMERY_R = { type = "u256", value = "0x7fffffffffffdf0ffffffffffffffffffffffffffffffffffffffffffffffe1", comment = "3618502788666127798953978732740734578953660990361066340291730267701097005025" }
K_MONTGOMERY_R_INV = { type = "u256", value = "0x40000000000001100000000000012100000000000000000000000000000000", comment = "113078212145816603762751633895895194930089271709401121343797004406777446400" }
LAYOUT_CODE = { type = "u256", value = "42800643258479064999893963318903811951182475189843316", comment = "42800643258479064999893963318903811951182475189843316" }
LOG_CPU_COMPONENT_HEIGHT = { type = "u256", value = "4", comment = "4" }
MASK_SIZE = { type = "u64", value = "192", comment = "192" }
MAX_COSET_SIZE = { type = "u256", value = "1 << FRI_MAX_STEP_SIZE", comment = "2^FRI_MAX_STEP_SIZE" }
MAX_FRI_STEPS = { type = "u64", value = "10", comment = "10" }
MAX_N_MERKLE_VERIFIER_QUERIES = { type = "u64", value = "128", comment = "128" }
MAX_N_QUERIES = { type = "u64", value = "48", comment = "48" }
MAX_SUPPORTED_FRI_STEP_SIZE = { type = "u64", value = "4", comment = "4" }
MAX_UINT128 = { type = "u256", value = "340282366920938463463374607431768211455", comment = "2 ^ 128 - 1" }
MAX_UINT192 = { type = "u256", value = "6277101735386680763835789423207666416102355444464034512895", comment = "2 ^ 192 - 1" }
MEMORY_PAIR_SIZE = { type = "u256", value = "2", comment = "2" }
MERKLE_SLOT_SIZE_IN_BYTES = { type = "u64", value = "64", comment = "64" }
MERKLE_UPDATE_OFFSET = { type = "u64", value = "0", comment = "0" }
MESSAGE_TO_L1_FROM_ADDRESS_OFFSET = { type = "u64", value = "0", comment = "0" }
MESSAGE_TO_L1_PAYLOAD_SIZE_OFFSET = { type = "u64", value = "2", comment = "2" }
MESSAGE_TO_L1_PREFIX_SIZE = { type = "u64", value = "3", comment = "3" }
MESSAGE_TO_L1_TO_ADDRESS_OFFSET = { type = "u64", value = "1", comment = "1" }
MESSAGE_TO_L2_FROM_ADDRESS_OFFSET = { type = "u64", value = "0", comment = "0" }
MESSAGE_TO_L2_NONCE_OFFSET = { type = "u64", value = "2", comment = "2" }
MESSAGE_TO_L2_PAYLOAD_SIZE_OFFSET = { type = "u64", value = "4", comment = "4" }
MESSAGE_TO_L2_PREFIX_SIZE = { type = "u64", value = "5", comment = "5" }
MESSAGE_TO_L2_SELECTOR_OFFSET = { type = "u64", value = "3", comment = "3" }
MESSAGE_TO_L2_TO_ADDRESS_OFFSET = { type = "u64", value = "1", comment = "1" }
METADATA_OFFSET_TASK_N_TREE_PAIRS = { type = "u64", value = "2", comment = "2" }
METADATA_OFFSET_TASK_OUTPUT_SIZE = { type = "u64", value = "0", comment = "0" }
METADATA_OFFSET_TASK_PROGRAM_HASH = { type = "u64", value = "1", comment = "1" }
METADATA_TASKS_OFFSET = { type = "u64", value = "1", comment = "1" }
METADATA_TASK_HEADER_SIZE = { type = "u64", value = "3", comment = "3" }
MM_BLOW_UP_FACTOR = { type = "u64", value = "1", comment = "1" }
MM_CHANNEL = { type = "u64", value = "10", comment = "10" }
MM_COMPOSITION_ALPHA = { type = "u64", value = "358", comment = "358" }
MM_COMPOSITION_OODS_VALUES = { type = "u64", value = "551", comment = "551" }
MM_COMPOSITION_QUERY_RESPONSES = { type = "u64", value = "1178", comment = "1178" }
MM_CONSTRAINT_POLY_ARGS_END = { type = "u64", value = "551", comment = "551" }
MM_CONSTRAINT_POLY_ARGS_START = { type = "u64", value = "317", comment = "317" }
MM_CONTEXT_SIZE = { type = "u64", value = "1277", comment = "1277" }
MM_DILUTED_CHECK__FINAL_CUM_VAL = { type = "u64", value = "343", comment = "343" }
MM_DILUTED_CHECK__FIRST_ELM = { type = "u64", value = "340", comment = "340" }
MM_DILUTED_CHECK__INTERACTION_ALPHA = { type = "u64", value = "342", comment = "342" }
MM_DILUTED_CHECK__INTERACTION_Z = { type = "u64", value = "341", comment = "341" }
MM_DILUTED_CHECK__PERMUTATION__INTERACTION_ELM = { type = "u64", value = "338", comment = "338" }
MM_DILUTED_CHECK__PERMUTATION__PUBLIC_MEMORY_PROD = { type = "u64", value = "339", comment = "339" }
MM_EVAL_DOMAIN_GENERATOR = { type = "u64", value = "4", comment = "4" }
MM_EVAL_DOMAIN_SIZE = { type = "u64", value = "0", comment = "0" }
MM_FINAL_AP = { type = "u64", value = "329", comment = "329" }
MM_FINAL_PC = { type = "u64", value = "330", comment = "330" }
MM_FRI_COMMITMENTS = { type = "u64", value = "305", comment = "305" }
MM_FRI_CTX = { type = "u64", value = "254", comment = "254" }
MM_FRI_EVAL_POINTS = { type = "u64", value = "295", comment = "295" }
MM_FRI_LAST_LAYER_DEG_BOUND = { type = "u64", value = "315", comment = "315" }
MM_FRI_LAST_LAYER_PTR = { type = "u64", value = "316", comment = "316" }
MM_FRI_QUERIES_DELIMITER = { type = "u64", value = "253", comment = "253" }
MM_FRI_QUEUE = { type = "u64", value = "109", comment = "109" }
MM_FRI_STEP_SIZES_PTR = { type = "u64", value = "294", comment = "294" }
MM_HALF_OFFSET_SIZE = { type = "u64", value = "326", comment = "326" }
MM_INITIAL_AP = { type = "u64", value = "327", comment = "327" }
MM_INITIAL_BITWISE_ADDR = { type = "u64", value = "348", comment = "348" }
MM_INITIAL_PC = { type = "u64", value = "328", comment = "328" }
MM_INITIAL_PEDERSEN_ADDR = { type = "u64", value = "346", comment = "346" }
MM_INITIAL_POSEIDON_ADDR = { type = "u64", value = "349", comment = "349" }
MM_INITIAL_RANGE_CHECK_ADDR = { type = "u64", value = "347", comment = "347" }
MM_INTERACTION_ELEMENTS = { type = "u64", value = "352", comment = "352" }
MM_LOG_EVAL_DOMAIN_SIZE = { type = "u64", value = "2", comment = "2" }
MM_LOG_N_STEPS = { type = "u64", value = "1274", comment = "1274" }
MM_MEMORY__MULTI_COLUMN_PERM__HASH_INTERACTION_ELM0 = { type = "u64", value = "332", comment = "332" }
MM_MEMORY__MULTI_COLUMN_PERM__PERM__INTERACTION_ELM = { type = "u64", value = "331", comment = "331" }
MM_MEMORY__MULTI_COLUMN_PERM__PERM__PUBLIC_MEMORY_PROD = { type = "u64", value = "333", comment = "333" }
MM_MERKLE_QUEUE = { type = "u64", value = "13", comment = "13" }
MM_N_PUBLIC_MEM_ENTRIES = { type = "u64", value = "1275", comment = "1275" }
MM_N_PUBLIC_MEM_PAGES = { type = "u64", value = "1276", comment = "1276" }
MM_N_UNIQUE_QUERIES = { type = "u64", value = "9", comment = "9" }
MM_OFFSET_SIZE = { type = "u64", value = "325", comment = "325" }
MM_OODS_ALPHA = { type = "u64", value = "601", comment = "601" }
MM_OODS_COMMITMENT = { type = "u64", value = "8", comment = "8" }
MM_OODS_EVAL_POINTS = { type = "u64", value = "553", comment = "553" }
MM_OODS_POINT = { type = "u64", value = "351", comment = "351" }
MM_OODS_VALUES = { type = "u64", value = "359", comment = "359" }
MM_PEDERSEN__SHIFT_POINT_X = { type = "u64", value = "344", comment = "344" }
MM_PEDERSEN__SHIFT_POINT_Y = { type = "u64", value = "345", comment = "345" }
MM_PERIODIC_COLUMN__PEDERSEN__POINTS__X = { type = "u64", value = "317", comment = "317" }
MM_PERIODIC_COLUMN__PEDERSEN__POINTS__Y = { type = "u64", value = "318", comment = "318" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY0 = { type = "u64", value = "319", comment = "319" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY1 = { type = "u64", value = "320", comment = "320" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__FULL_ROUND_KEY2 = { type = "u64", value = "321", comment = "321" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__PARTIAL_ROUND_KEY0 = { type = "u64", value = "322", comment = "322" }
MM_PERIODIC_COLUMN__POSEIDON__POSEIDON__PARTIAL_ROUND_KEY1 = { type = "u64", value = "323", comment = "323" }
MM_PROOF_OF_WORK_BITS = { type = "u64", value = "3", comment = "3" }
MM_PUBLIC_INPUT_PTR = { type = "u64", value = "5", comment = "5" }
MM_RANGE_CHECK16__PERM__INTERACTION_ELM = { type = "u64", value = "334", comment = "334" }
MM_RANGE_CHECK16__PERM__PUBLIC_MEMORY_PROD = { type = "u64", value = "335", comment = "335" }
MM_RANGE_CHECK_MAX = { type = "u64", value = "337", comment = "337" }
MM_RANGE_CHECK_MIN = { type = "u64", value = "336", comment = "336" }
MM_TRACE_COMMITMENT = { type = "u64", value = "6", comment = "6" }
MM_TRACE_GENERATOR = { type = "u64", value = "350", comment = "350" }
MM_TRACE_LENGTH = { type = "u64", value = "324", comment = "324" }
MM_TRACE_QUERY_RESPONSES = { type = "u64", value = "602", comment = "602" }
N_COEFFICIENTS = { type = "u256", value = "124", comment = "124" }
N_COLUMNS_IN_MASK = { type = "u64", value = "12", comment = "12" }
N_COLUMNS_IN_TRACE0 = { type = "u64", value = "9", comment = "9" }
N_COLUMNS_IN_TRACE1 = { type = "u64", value = "3", comment = "3" }
N_INTERACTION_ELEMENTS = { type = "u64", value = "6", comment = "6" }
N_OODS_COEFFICIENTS = { type = "u64", value = "N_OODS_VALUES", comment = "N_OODS_VALUES" }
N_OODS_VALUES = { type = "u64", value = "MASK_SIZE + CONSTRAINTS_DEGREE_BOUND", comment = "MASK_SIZE + CONSTRAINTS_DEGREE_BOUND" }
N_ROWS_IN_MASK = { type = "u256", value = "98", comment = "98" }
OFFSET_BITWISE_BEGIN_ADDR = { type = "u64", value = "14", comment = "14" }
OFFSET_BITWISE_STOP_ADDR = { type = "u64", value = "15", comment = "15" }
OFFSET_EXECUTION_BEGIN_ADDR = { type = "u64", value = "6", comment = "6" }
OFFSET_EXECUTION_STOP_PTR = { type = "u64", value = "7", comment = "7" }
OFFSET_LAYOUT_CODE = { type = "u64", value = "3", comment = "3" }
OFFSET_LOG_N_STEPS = { type = "u64", value = "0", comment = "0" }
OFFSET_N_PUBLIC_MEMORY_PAGES = { type = "u64", value = "20", comment = "20" }
OFFSET_OUTPUT_BEGIN_ADDR = { type = "u64", value = "8", comment = "8" }
OFFSET_OUTPUT_STOP_PTR = { type = "u64", value = "9", comment = "9" }
OFFSET_PEDERSEN_BEGIN_ADDR = { type = "u64", value = "10", comment = "10" }
OFFSET_PEDERSEN_STOP_PTR = { type = "u64", value = "11", comment = "11" }
OFFSET_POSEIDON_BEGIN_ADDR = { type = "u64", value = "16", comment = "16" }
OFFSET_POSEIDON_STOP_PTR = { type = "u64", value = "17", comment = "17" }
OFFSET_PROGRAM_BEGIN_ADDR = { type = "u64", value = "4", comment = "4" }
OFFSET_PROGRAM_STOP_PTR = { type = "u64", value = "5", comment = "5" }
OFFSET_PUBLIC_MEMORY = { type = "u64", value = "21", comment = "21" }
OFFSET_PUBLIC_MEMORY_PADDING_ADDR = { type = "u64", value = "18", comment = "18" }
OFFSET_PUBLIC_MEMORY_PADDING_VALUE = { type = "u64", value = "19", comment = "19" }
OFFSET_RANGE_CHECK_BEGIN_ADDR = { type = "u64", value = "12", comment = "12" }
OFFSET_RANGE_CHECK_STOP_PTR = { type = "u64", value = "13", comment = "13" }
OFFSET_RC_MAX = { type = "u64", value = "2", comment = "2" }
OFFSET_RC_MIN = { type = "u64", value = "1", comment = "1" }
ONE_VAL = { type = "u256", value = "1", comment = "1" }
OUTPUT_BUILTIN_BIT = { type = "u256", value = "0", comment = "0" }
PAGE_INFO_ADDRESS_OFFSET = { type = "u256", value = "0", comment = "0" }
PAGE_INFO_HASH_OFFSET = { type = "u256", value = "2", comment = "2" }
PAGE_INFO_SIZE = { type = "u256", value = "3", comment = "3" }
PAGE_INFO_SIZE_IN_BYTES = { type = "u256", value = "3 * 32", comment = "3 * 32" }
PAGE_INFO_SIZE_OFFSET = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_BIT = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_RATIO = { type = "u256", value = "128", comment = "128" }
PEDERSEN_BUILTIN_REPETITIONS = { type = "u256", value = "1", comment = "1" }
PEDERSEN_BUILTIN_ROW_RATIO = { type = "u256", value = "2048", comment = "2048" }
POINT_EVALUATION_PRECOMPILE_OUTPUT = { type = "vector<u8>", value = 'x"b2157d3a40131b14c4c675335465dffde802f0ce5218ad012284d7f275d1b37c"', comment = "b2157d3a40131b14c4c675335465dffde802f0ce5218ad012284d7f275d1b37c" }
POSEIDON_BUILTIN_BIT = { type = "u256", value = "7", comment = "7" }
POSEIDON__M = { type = "u256", value = "3", comment = "3" }
POSEIDON__RATIO = { type = "u256", value = "8", comment = "8" }
POSEIDON__ROUNDS_FULL = { type = "u256", value = "8", comment = "8" }
POSEIDON__ROUNDS_PARTIAL = { type = "u256", value = "83", comment = "83" }
POSEIDON__ROW_RATIO = { type = "u256", value = "128", comment = "128" }
PROGRAM_HASH_TAG = { type = "vector<u8>", value = 'b"STARKNET_1.0_INIT_PROGRAM_HASH_UINT"', comment = "Random storage slot tags" }
PROGRAM_SIZE = { type = "u256", value = "728", comment = "728" }
PROOF_BYTES_LENGTH = { type = "u256", value = "48", comment = "48" }
PROOF_PARAMS_FRI_STEPS_OFFSET = { type = "u64", value = "5", comment = "5" }
PROOF_PARAMS_N_FRI_STEPS_OFFSET = { type = "u64", value = "4", comment = "4" }
PUBLIC_MEMORY_STEP = { type = "u256", value = "16", comment = "16" }
RANGE_CHECK_BUILTIN_BIT = { type = "u256", value = "2", comment = "2" }
RANGE_CHECK_BUILTIN_RATIO = { type = "u256", value = "8", comment = "8" }
RANGE_CHECK_BUILTIN_ROW_RATIO = { type = "u256", value = "128", comment = "128" }
RANGE_CHECK_N_PARTS = { type = "u256", value = "8", comment = "8" }
REGULAR_PAGE = { type = "u256", value = "0", comment = "0" }
STATE_STRUCT_TAG = { type = "vector<u8>", value = 'b"STARKNET_1.0_INIT_STARKNET_STATE_STRUCT"', comment = "STARKNET_1.0_INIT_STARKNET_STATE_STRUCT" }
TWO_COMMITMENTS_SIZE_IN_BYTES = { type = "u64", value = "64", comment = "64" }
USE_KZG_DA_OFFSET = { type = "u64", value = "5", comment = "5" }
VERIFIER_ADDRESS_TAG = { type = "vector<u8>", value = 'b"STARKNET_1.0_INIT_VERIFIER_ADDRESS"', comment = "STARKNET_1.0_INIT_VERIFIER_ADDRESS" }
VERSIONED_HASH_VERSION_KZG = { type = "vector<u8>", value = 'x"01"', comment = "01" }
